// Meter audit — Josh's barline test, mechanized (2026-08-05 handoff).
// For each song: find each channel's dominant repeating figure period
// (autocorrelation of onset positions), and test which candidate bar
// lengths that period divides into. A dominant figure that phases across
// the barlines means the barline is wrong (shop failed 4/4 exactly this
// way). Second pass: within-bar onset grouping (duple vs triple insides)
// and pulse-channel volume accents distinguish 3/4 from 6/8 once the bar
// length is right.
//
// OUTPUT IS QUARANTINED: full findings go to
// albums/final-fantasy-i/reference/meter-audit.md — a computed meter is a
// guess, and the app/repo must never volunteer one for a song Josh hasn't
// determined. Run: node tools/nsf/meter_audit.mjs
import { createApp } from "../../tests/harness.mjs";
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.dirname(path.dirname(path.dirname(fileURLToPath(import.meta.url))));
const SONGS = path.join(ROOT, "albums/final-fantasy-i/songs");
const OUT = path.join(ROOT, "albums/final-fantasy-i/reference/meter-audit.md");
const CANDIDATES = [2, 3, 4, 6]; // bar lengths in quarter notes (2/4, 3/4 | 6/8, 4/4, 6/4 | 12/8)

function analyze(file) {
  const app = createApp();
  app.context.midiBytes = [...readFileSync(path.join(SONGS, file))];
  return JSON.parse(app.run(`JSON.stringify((() => {
    const r = parseMidi(new Uint8Array(midiBytes).buffer);
    const Q = r.ppq;
    const chans = r.tracks.filter(t => t.notes.length > 3).map(t => {
      // onset vector on a 16th grid
      const g = Q / 4;
      const set = new Set(t.notes.map(n => Math.round(n.t / g)));
      const max = Math.max(...set);
      // dominant figure period: smallest lag (in 16ths, >= 4) where most
      // onsets recur
      let best = null;
      for (let lag = 4; lag <= Math.min(96, max / 2); lag++) {
        let hit = 0, tries = 0;
        for (const o of set) { if (o + lag <= max) { tries++; if (set.has(o + lag)) hit++; } }
        if (tries < 8) continue;
        const score = hit / tries;
        if (score > 0.8 && (!best || lag < best.lag)) best = {lag, score};
      }
      // within-bar position mass for grouping evidence, per candidate handled outside
      const onsets = [...set];
      const vels = {};
      t.notes.forEach(n => { const p16 = Math.round(n.t / g); vels[p16] = Math.max(vels[p16] || 0, n.v); });
      return {name: t.name, figure16: best ? best.lag : null, figScore: best ? +best.score.toFixed(2) : null,
              onsets, vels, count: t.notes.length};
    });
    let end = 0;
    r.tracks.forEach(t => t.notes.forEach(n => end = Math.max(end, n.t + n.d)));
    return {ts: r.timesig.join("/"), bpm: Math.round(6e7 / r.tempos[0].usq),
            endQ: end / Q, chans};
  })())`));
}

const report = ["# Meter audit — computed best-fits. SPOILER-QUARANTINED.",
  "",
  "Generated by tools/nsf/meter_audit.mjs. Everything below is a GUESS",
  "computed from onset periodicity, within-bar grouping, and pulse volume",
  "accents. It is evidence to consult when stuck — never a finding. Songs",
  "whose meter Josh has determined are marked; the rest are his to rule.",
  ""];
const chatSummary = [];

for (const f of readdirSync(SONGS).filter(f => f.endsWith(".mid")).sort()) {
  const base = f.replace(/\.mid$/, "");
  const a = analyze(f);
  const rn = path.join(SONGS, base + ".rollnotes.json");
  const declared = existsSync(rn) &&
    (readFileSync(rn, "utf8").match(/^timesig:\s*(\d+\/\d+)/m) || [])[1];
  const curQ = (() => { const [n, d] = a.ts.split("/").map(Number); return n * 4 / d; })();

  // figure-period barline test against the current (header) meter
  const figs = a.chans.filter(c => c.figure16).map(c =>
    ({name: c.name, q: c.figure16 / 4, score: c.figScore}));
  const failing = figs.filter(fg => {
    const bar16 = curQ * 4;
    return (bar16 % c16(fg.q)) !== 0 && (c16(fg.q) % bar16) !== 0;
  });
  function c16(q) { return Math.round(q * 4); }

  // candidate bars: every figure period must divide (or be divided by) the bar
  const survivors = CANDIDATES.filter(B => figs.every(fg =>
    (B * 4) % c16(fg.q) === 0 || c16(fg.q) % (B * 4) === 0));

  report.push("## " + base + (declared ? "  — meter DECLARED by Josh: " + declared : ""));
  report.push("");
  report.push("- header meter " + a.ts + " at " + a.bpm + "bpm; length " + a.endQ.toFixed(1) + " quarters");
  report.push("- dominant figure periods: " + (figs.length ? figs.map(fg =>
    fg.name + " = " + fg.q + "q (self-similarity " + fg.score + ")").join(", ") : "none found (through-composed or too varied)"));
  report.push("- barline test vs current meter: " + (failing.length
    ? "**FAILS** on " + failing.map(fg => fg.name).join(", ") + " — figure phases across barlines"
    : figs.length ? "passes" : "inconclusive"));
  report.push("- candidate bar lengths (quarters) consistent with every figure: " +
    (survivors.length ? survivors.join(", ") : "none — rhythmically irregular or detector limitation"));
  if (survivors.length > 1) report.push("- verdict: **ambiguous** between " + survivors.join("/") + " — grouping/accent evidence needed (Josh's call)");
  report.push("");

  if (failing.length && !declared) chatSummary.push(base);
}

writeFileSync(OUT, report.join("\n") + "\n");
console.log("report -> albums/final-fantasy-i/reference/meter-audit.md");
console.log(chatSummary.length
  ? "songs whose CURRENT header meter fails the barline test (undetermined, details quarantined): " + chatSummary.join(", ")
  : "no undetermined song fails the barline test against its current header meter");
